const A='assets/exercises/';
const raw=[
['lunge','Utfall','Lunge','Framåtutfall|Gående utfall|Forward lunge|Walking lunge','Ben','Nybörjare','8 min','Lår|Säte','Stående','En enbensövning som tränar lår, säte, balans och bålstabilitet.','A unilateral exercise that builds leg strength, glutes, balance and core stability.','Stå höftbrett med neutral rygg.|Ta ett kontrollerat steg framåt.|Sänk bakre knät och håll främre knät i linje med foten.|Pressa genom främre foten tillbaka till start.','Stand hip-width with a neutral spine.|Take a controlled step forward.|Lower the back knee and align the front knee with the foot.|Push through the front foot to return.','Bakåtutfall · Reverse lunge|Gående utfall · Walking lunge|Utfall med stöd · Assisted lunge'],
['squat','Knäböj','Squat','Benböj|Air squat|Bodyweight squat','Ben','Nybörjare','10 min','Lår|Säte','Stående','En grundövning för ben och höfter som också stärker bålen.','A foundational movement for legs and hips that also strengthens the core.','Stå ungefär axelbrett.|Sänk höfterna bakåt och nedåt.|Pressa golvet ifrån dig och res dig.','Stand about shoulder-width.|Lower the hips back and down.|Push the floor away and stand tall.','Knäböj till stol · Chair squat|Sumoknäböj · Sumo squat|Hoppknäböj · Jump squat'],
['pushup','Armhävning','Push-up','Pushup|Press-up|Bröstpress på golv','Överkropp','Medel','6 min','Bröst|Triceps|Axlar','Magläge','Tränar bröst, axlar, triceps och bål med kroppen som motstånd.','Builds the chest, shoulders, triceps and core using bodyweight resistance.','Placera händerna strax bredare än axlarna.|Håll kroppen i en rak linje.|Sänk bröstet kontrollerat och pressa upp.','Place hands slightly wider than shoulders.|Keep the body in a straight line.|Lower with control and press up.','Armhävning mot vägg · Wall push-up|Armhävning på knä · Knee push-up|Smal armhävning · Diamond push-up'],
['plank','Plankan','Plank','Underarmsplanka|Front plank|Forearm plank','Bål','Nybörjare','5 min','Bål|Axlar','Magläge','En statisk övning som utvecklar uthållighet och kontroll i bålen.','An isometric exercise that develops endurance and control throughout the core.','Placera armbågarna under axlarna.|Spänn mage och säte.|Behåll en rak linje och andas lugnt.','Place elbows under shoulders.|Brace the core and glutes.|Hold a straight line and breathe calmly.','Planka på knä · Knee plank|Hög planka · High plank|Sidoplanka · Side plank'],
['bridge','Höftlyft','Glute bridge','Bäckenlyft|Glute bridge|Hip bridge','Ben','Nybörjare','7 min','Säte|Baksida lår','Ryggläge','Aktiverar säte och baksida lår samtidigt som höften tränas i extension.','Activates glutes and hamstrings while training hip extension.','Ligg på rygg med böjda knän.|Pressa fötterna i golvet.|Lyft höften och spänn sätet.','Lie on your back with knees bent.|Press the feet into the floor.|Lift the hips and squeeze the glutes.','Enbenshöftlyft · Single-leg bridge|Höftlyft med paus · Paused bridge|Marscherande höftlyft · Bridge march'],
['deadbug','Död insekt','Dead bug','Dead bug exercise|Motsatt arm och ben','Bål','Medel','6 min','Bål','Ryggläge','Tränar djup bålstabilitet och koordination med låg belastning på ryggen.','Trains deep core stability and coordination with low load on the back.','Ligg på rygg med armar och ben upp.|Pressa ländryggen lätt mot golvet.|Sänk motsatt arm och ben långsamt.','Lie on your back with arms and legs raised.|Gently press the lower back down.|Slowly lower the opposite arm and leg.','Endast ben · Legs only|Hälisättning · Heel taps|Dead bug med gummiband · Banded dead bug'],
['row','Rodd med gummiband','Band row','Sittande rodd|Resistance band row|Seated band row','Överkropp','Nybörjare','8 min','Rygg|Biceps','Sittande, ben framåt','En dragövning för övre rygg, skuldror och armar.','A pulling exercise for the upper back, shoulder blades and arms.','Sitt långt med bandet runt fötterna.|Dra armbågarna bakåt nära kroppen.|För händerna långsamt fram igen.','Sit tall with the band around the feet.|Pull elbows back close to the body.|Return the hands forward slowly.','Enarmsrodd · One-arm row|Brett grepp · Wide-grip row|Stående rodd · Standing row'],
['calf','Tåhävning','Calf raise','Vadpress|Heel raise|Standing calf raise','Ben','Nybörjare','5 min','Vader','Stående','Stärker vader och fotleder och kan förbättra balans.','Strengthens calves and ankles and may improve balance.','Stå upprätt med jämn vikt.|Lyft hälarna så högt du kan.|Sänk långsamt tillbaka.','Stand tall with even pressure.|Lift the heels as high as comfortable.|Lower back down slowly.','Med stöd · Assisted calf raise|Enbens tåhävning · Single-leg calf raise|Sittande tåhävning · Seated calf raise'],
['birddog','Fågelhund','Bird dog','Diagonallyft|Quadruped reach|Bird-dog','Bål','Nybörjare','6 min','Bål|Rygg|Säte','Fyrfota','En kontrollerad diagonalövning för stabilitet, balans och rygg.','A controlled diagonal exercise for stability, balance and the back.','Stå på alla fyra med neutral rygg.|Sträck motsatt arm och ben.|Pausa och återgå utan att rotera höften.','Start on all fours with a neutral spine.|Extend the opposite arm and leg.|Pause and return without rotating the hips.','Endast arm · Arm only|Endast ben · Leg only|Armbåge mot knä · Elbow-to-knee bird dog'],
['superman','Superman','Superman','Rygglyft på mage|Prone back extension','Rygg','Medel','6 min','Rygg|Säte','Magläge','En magliggande ryggövning för kroppens baksida.','A prone back exercise for the posterior chain.','Ligg på mage med armarna framåt.|Spänn sätet och lyft lätt.|Pausa kort och sänk kontrollerat.','Lie face down with arms forward.|Brace the glutes and lift gently.|Pause briefly and lower with control.','Växelvis superman · Alternating superman|Endast överkropp · Upper body only|Simtag · Swimmer'],
['sideleg','Sidoliggande benlyft','Side-lying leg raise','Höftabduktion sidoliggande|Side leg lift','Rörlighet','Nybörjare','7 min','Säte|Höft','Sidoläge','Stärker höftens utsida och förbättrar kontrollen kring bäckenet.','Strengthens the outer hip and improves control around the pelvis.','Ligg på sidan med raka, staplade ben.|Lyft övre benet utan att rulla bakåt.|Sänk långsamt med kontroll.','Lie on your side with legs stacked.|Lift the top leg without rolling back.|Lower slowly with control.','Böjt stödben · Bent support leg|Små pulser · Small pulses|Med gummiband · Banded leg raise'],
['seatedtwist','Sittande rotation','Seated twist','Bålrotation sittande|Seated torso rotation','Rörlighet','Nybörjare','5 min','Bål|Rygg','Sittande, ben framåt','En lugn rotation som tränar bröstryggens rörlighet och bålens kontroll.','A gentle rotation for thoracic mobility and core control.','Sitt högt med benen framåt.|Rotera bröstkorgen utan att flytta höfterna.|Återgå och upprepa åt andra hållet.','Sit tall with legs forward.|Rotate the chest without moving the hips.|Return and repeat on the other side.','På stol · Chair rotation|Med böjda knän · Bent-knee twist|Med pinne · Dowel rotation'],
['jumpingjack','Krysshopp','Jumping jack','Sprattelgubbe|Star jump|Jumping jack','Puls','Nybörjare','5 min','Helkropp|Vader','Stående','En enkel helkroppsrörelse som höjer pulsen och tränar koordination.','A simple full-body movement that raises the heart rate and trains coordination.','Stå med fötterna ihop och armarna ned.|Hoppa isär samtidigt som armarna förs upp.|Hoppa tillbaka mjukt och rytmiskt.','Stand with feet together and arms down.|Jump apart while raising the arms.|Jump back softly and rhythmically.','Utan hopp · Step jack|Halva krysshopp · Half jack|Snabba krysshopp · Power jack']];
const data=raw.map(r=>{const [id,sv,en,aliases,cat,level,time,muscles,position,descSv,descEn,stepsSv,stepsEn,variations]=r;return{id,sv,en,aliases:aliases.split('|'),cat,level,time,muscles:muscles.split('|'),position,descSv,descEn,stepsSv:stepsSv.split('|'),stepsEn:stepsEn.split('|'),variations:variations.split('|'),images:[1,2,3].map(n=>`${A}${id}-${n}.png`),image:`${A}${id}-2.png`}});
const state={language:localStorage.getItem('flex-language')||'both',filter:'Alla',query:'',view:localStorage.getItem('flex-view')||'cards',saved:new Set(JSON.parse(localStorage.getItem('flex-saved')||'[]')),collection:null};
const $=s=>document.querySelector(s),grid=$('#exerciseGrid'),filters=$('#filters'),count=$('#resultCount'),empty=$('#emptyState');
const categoryLabels={Alla:'Alla · All',Ben:'Ben · Legs',Överkropp:'Överkropp · Upper body',Bål:'Bål · Core',Rygg:'Rygg · Back',Rörlighet:'Rörlighet · Mobility',Puls:'Puls · Cardio'};
const primary=e=>state.language==='en'?e.en:e.sv,secondary=e=>state.language==='both'?(primary(e)===e.sv?e.en:e.sv):'';
function setupFilters(){filters.innerHTML=Object.keys(categoryLabels).map(c=>`<button class="filter ${state.filter===c?'active':''}" data-filter="${c}">${categoryLabels[c]}</button>`).join('')}
function currentItems(){if(state.collection)return data.filter(e=>state.collection.ids.includes(e.id));const q=state.query.toLowerCase().trim();return data.filter(e=>(state.filter==='Alla'||e.cat===state.filter)&&(`${e.sv} ${e.en} ${e.aliases} ${e.cat} ${e.muscles}`).toLowerCase().includes(q))}
function saveButton(e){return`<button class="save ${state.saved.has(e.id)?'saved':''}" data-save="${e.id}" aria-label="Spara ${e.sv}">${state.saved.has(e.id)?'♥':'♡'}</button>`}
function card(e){return`<article class="exercise-card">${saveButton(e)}<button class="card-open" data-id="${e.id}"><span class="card-art"><img src="${e.image}" alt="${e.sv} – ${e.en}" loading="lazy"><span class="card-badge">${e.cat}</span></span><span class="card-copy"><h3>${primary(e)}</h3>${secondary(e)?`<p class="secondary">${secondary(e)}</p>`:''}<span class="meta"><span>◷ ${e.time}</span><span>◇ ${e.level}</span></span></span></button></article>`}
function row(e){return`<article class="exercise-row"><button class="row-main" data-id="${e.id}"><span class="row-category">${e.cat}</span><span><strong>${primary(e)}</strong>${secondary(e)?`<small>${secondary(e)}</small>`:''}</span><span class="row-muscles">${e.muscles.join(' · ')}</span><span class="row-meta">${e.level} · ${e.time}</span><span class="row-arrow">›</span></button>${saveButton(e)}</article>`}
function render(){const found=currentItems();grid.className=state.view==='list'?'exercise-list':'exercise-grid';grid.innerHTML=found.map(state.view==='list'?row:card).join('');count.textContent=`${found.length} övningar`;empty.hidden=found.length>0;$('#collectionBanner').hidden=!state.collection;if(state.collection)$('#collectionTitle').textContent=state.collection.title}
function relatedCard(e){return`<button class="related-card" data-related="${e.id}"><img src="${e.image}" alt=""><span><b>${primary(e)}</b>${secondary(e)?`<small>${secondary(e)}</small>`:''}</span><i>›</i></button>`}
function relation(title,items,label){if(!items.length)return'';return`<section class="relation"><div class="relation-head"><div><span>${label}</span><h3>${title}</h3></div><button data-collection="${items.map(x=>x.id)}" data-title="${title}">Visa alla · View all</button></div><div class="related-strip">${items.slice(0,4).map(relatedCard).join('')}</div></section>`}
function openExercise(id){const e=data.find(x=>x.id===id),sameMuscle=data.filter(x=>x.id!==id&&x.muscles.some(m=>e.muscles.includes(m))),samePosition=data.filter(x=>x.id!==id&&x.position===e.position),steps=state.language==='en'?e.stepsEn:e.stepsSv;$('#detailContent').innerHTML=`<div class="gallery" id="gallery">${e.images.map((img,i)=>`<figure><img src="${img}" alt="${e.sv}, steg ${i+1}"><figcaption>Steg ${i+1} · Step ${i+1}</figcaption></figure>`).join('')}</div><div class="dots">${e.images.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide="${i}" aria-label="Visa steg ${i+1}"></button>`).join('')}</div><div class="detail-copy"><span class="tag">${e.cat} · ${e.level}</span><button class="name-toggle" aria-expanded="false"><span><h2 id="detailTitle">${primary(e)}</h2>${secondary(e)?`<p class="translated">${secondary(e)}</p>`:''}</span><i>⌄</i></button><div class="aliases" hidden><span>FLER NAMN · OTHER NAMES</span>${e.aliases.map(n=>`<b>${n}</b>`).join('')}</div><p class="description">${state.language==='en'?e.descEn:e.descSv}${state.language==='both'?`<br><br>${e.descEn}`:''}</p><div class="stats"><div class="stat"><span>Tid · Time</span><b>${e.time}</b></div><div class="stat"><span>Position</span><b>${e.position}</b></div><div class="stat"><span>Fokus · Focus</span><b>${e.muscles.join(' · ')}</b></div></div><div class="instructions"><h3>${state.language==='en'?'How to do it':'Så gör du'}${state.language==='both'?' · How to do it':''}</h3><ol>${steps.map(s=>`<li>${s}</li>`).join('')}</ol></div>${relation(e.muscles.join(' & '),sameMuscle,'SAMMA MUSKELGRUPP · SAME MUSCLES')}${relation(e.position,samePosition,'SAMMA POSITION · SAME POSITION')}<section class="relation"><div class="relation-head"><div><span>VARIATIONER · VARIATIONS</span><h3>Andra sätt att göra övningen</h3></div></div><div class="variation-list">${e.variations.map((v,i)=>`<div><span>${i===0?'Lättare':i===2?'Svårare':'Alternativ'}</span><b>${v}</b></div>`).join('')}</div></section></div>`;const modal=$('#exerciseModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('body-locked');const gallery=$('#gallery'),dots=[...document.querySelectorAll('.dot')];gallery.addEventListener('scroll',()=>{const i=Math.round(gallery.scrollLeft/gallery.clientWidth);dots.forEach((d,n)=>d.classList.toggle('active',n===i))},{passive:true});dots.forEach(d=>d.onclick=()=>gallery.scrollTo({left:+d.dataset.slide*gallery.clientWidth,behavior:'smooth'}));$('.name-toggle').onclick=e=>{const aliases=$('.aliases'),open=aliases.hidden;aliases.hidden=!open;e.currentTarget.setAttribute('aria-expanded',open)}}
function closeModal(){const m=$('#exerciseModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('body-locked')}
function showCollection(ids,title){closeModal();state.collection={ids,title};state.query='';$('#searchInput').value='';render();$('#libraryTitle').scrollIntoView({behavior:'smooth'})}
filters.onclick=e=>{if(e.target.dataset.filter){state.collection=null;state.filter=e.target.dataset.filter;setupFilters();render()}};grid.onclick=e=>{const s=e.target.closest('[data-save]');if(s){state.saved.has(s.dataset.save)?state.saved.delete(s.dataset.save):state.saved.add(s.dataset.save);localStorage.setItem('flex-saved',JSON.stringify([...state.saved]));render();return}const o=e.target.closest('[data-id]');if(o)openExercise(o.dataset.id)};
$('#detailContent').onclick=e=>{const r=e.target.closest('[data-related]');if(r){openExercise(r.dataset.related);return}const c=e.target.closest('[data-collection]');if(c)showCollection(c.dataset.collection.split(','),c.dataset.title)};$('#searchInput').oninput=e=>{state.collection=null;state.query=e.target.value;render()};
$('#viewToggle').onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;localStorage.setItem('flex-view',state.view);$('#viewToggle').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()};$('#clearCollection').onclick=()=>{state.collection=null;render()};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')closeModal()});document.querySelectorAll('[data-close]').forEach(el=>el.onclick=closeModal);
const languageButton=$('#languageButton'),languageMenu=$('#languageMenu');languageButton.onclick=()=>{languageMenu.hidden=!languageMenu.hidden;languageButton.setAttribute('aria-expanded',!languageMenu.hidden)};languageMenu.onclick=e=>{const lang=e.target.closest('[data-language]')?.dataset.language;if(!lang)return;state.language=lang;localStorage.setItem('flex-language',lang);$('#languageShort').textContent=lang==='both'?'SV + EN':lang.toUpperCase();languageMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.language===lang));languageMenu.hidden=true;render()};$('#savedLink').onclick=e=>{e.preventDefault();showCollection([...state.saved],'Sparade övningar · Saved exercises')};
$('#languageShort').textContent=state.language==='both'?'SV + EN':state.language.toUpperCase();languageMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.language===state.language));$('#viewToggle').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));setupFilters();render();

// Variation detail views. Existing variation rows become navigable without duplicating base exercise data.
const variationCues=[
 ['vägg','Flytta händerna till en stadig vägg och håll kroppen i en rak, lutande linje.','Place the hands on a sturdy wall and keep the body in a straight, inclined line.'],
 ['knä','Låt knäna ge stöd och behåll en rak linje från knä till huvud.','Use the knees for support and keep a straight line from knees to head.'],
 ['stol','Använd en stadig stol som tydligt mål och stöd under rörelsen.','Use a sturdy chair as a clear target and support during the movement.'],
 ['stöd','Håll lätt i ett stabilt stöd och fokusera på kontroll och rörelsebana.','Hold a stable support lightly and focus on control and range.'],
 ['enben','Flytta belastningen till ett ben och håll bäckenet vågrätt.','Shift the load to one leg and keep the pelvis level.'],
 ['enbens','Flytta belastningen till ett ben och håll bäckenet vågrätt.','Shift the load to one leg and keep the pelvis level.'],
 ['bakåt','Ta steget bakåt och behåll vikten jämnt över den främre foten.','Step backward and keep the weight even through the front foot.'],
 ['gående','Fortsätt framåt från varje repetition med bibehållen balans.','Continue forward from each repetition while maintaining balance.'],
 ['sumo','Stå bredare med tår och knän lätt riktade utåt.','Take a wider stance with toes and knees pointing slightly outward.'],
 ['hopp','Lägg till ett mjukt hopp och landa kontrollerat med böjda knän.','Add a soft jump and land with control and bent knees.'],
 ['paus','Stanna i rörelsens mest ansträngande läge utan att tappa positionen.','Pause at the hardest point without losing position.'],
 ['gummiband','Placera ett lätt träningsband så att motståndet ökar gradvis.','Position a light resistance band so tension increases gradually.'],
 ['endast','Minska rörelsen till den angivna kroppsdelen och håll resten stabil.','Limit the movement to the stated body part and keep everything else stable.'],
 ['växel','Arbeta sida för sida i ett lugnt och växlande tempo.','Work side to side at a calm alternating pace.'],
 ['utan hopp','Kliv ut åt sidan i stället för att hoppa och håll en jämn rytm.','Step out to the side instead of jumping and keep an even rhythm.']
];
function variationCue(name){const hit=variationCues.find(c=>name.toLowerCase().includes(c[0]));return hit?hit.slice(1):['Ändra den beskrivna delen och behåll grundövningens teknik i övrigt.','Change the described element and retain the base exercise technique otherwise.']}
function openVariation(base,index){const v=base.variations[index],[sv,en]=v.split(' · '),[cueSv,cueEn]=variationCue(v),difficulty=index===0?'Lättare · Easier':index===2?'Svårare · Harder':'Alternativ · Alternative',steps=state.language==='en'?base.stepsEn:base.stepsSv;$('#detailContent').innerHTML=`<div class="variation-hero"><img src="${base.image}" alt="${sv}"><span>${difficulty}</span></div><div class="detail-copy"><button class="back-to-base" data-related="${base.id}">‹ ${base.sv} · ${base.en}</button><h2 id="detailTitle">${state.language==='en'?en:sv}</h2>${state.language==='both'?`<p class="translated">${en}</p>`:''}<p class="description">${state.language==='en'?`This is a variation of ${base.en}. ${cueEn}`:`Det här är en variation av ${base.sv}. ${cueSv}`}${state.language==='both'?`<br><br>This is a variation of ${base.en}. ${cueEn}`:''}</p><div class="stats"><div class="stat"><span>Nivå · Level</span><b>${difficulty}</b></div><div class="stat"><span>Position</span><b>${base.position}</b></div><div class="stat"><span>Fokus · Focus</span><b>${base.muscles.join(' · ')}</b></div></div><div class="instructions"><h3>Så gör du · How to do it</h3><ol><li>${state.language==='en'?cueEn:cueSv}</li>${steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="variation-note">Avbryt om rörelsen gör ont och välj en bekväm rörelsebana. · Stop if the movement causes pain and use a comfortable range.</p></div><section class="relation"><div class="relation-head"><div><span>GRUNDÖVNING · BASE EXERCISE</span><h3>${base.sv} · ${base.en}</h3></div></div>${relatedCard(base)}</section></div>`}
$('#detailContent').addEventListener('click',event=>{const variation=event.target.closest('.variation-list div');if(!variation)return;const heading=$('#detailTitle')?.textContent;const base=data.find(item=>item.sv===heading||item.en===heading);if(base)openVariation(base,[...variation.parentElement.children].indexOf(variation))});
