const exercises = [
  {id:'lunge',sv:'Utfall',en:'Lunge',cat:'Ben',level:'Nybörjare',time:'8 min',icon:'01',color:'#d7eadf',image:'assets/exercises/lunge-2.png',descSv:'En klassisk enbensövning som tränar lår, säte, balans och bålstabilitet.',descEn:'A classic unilateral exercise that builds leg strength, glutes, balance and core stability.',stepsSv:['Stå höftbrett med lång, neutral rygg.','Ta ett kontrollerat steg framåt.','Sänk bakre knät mot golvet och håll främre knät i linje med foten.','Pressa genom främre foten tillbaka till start.'],stepsEn:['Stand hip-width with a tall, neutral spine.','Take a controlled step forward.','Lower the back knee and keep the front knee aligned with the foot.','Push through the front foot to return to standing.'],muscles:'Lår · Säte',images:['assets/exercises/lunge-1.png','assets/exercises/lunge-2.png','assets/exercises/lunge-3.png']},
  {id:'squat',sv:'Knäböj',en:'Squat',cat:'Ben',level:'Nybörjare',time:'10 min',icon:'02',color:'#eadfcf',descSv:'En grundövning för ben och höfter som också stärker din bål.',descEn:'A foundational movement for legs and hips that also strengthens your core.',muscles:'Lår · Säte',stepsSv:['Stå med fötterna ungefär axelbrett.','Sänk höfterna bakåt och nedåt.','Pressa golvet ifrån dig och res dig.'],stepsEn:['Stand with feet about shoulder-width apart.','Lower the hips back and down.','Push the floor away and stand tall.']},
  {id:'pushup',sv:'Armhävning',en:'Push-up',cat:'Överkropp',level:'Medel',time:'6 min',icon:'03',color:'#d9e3ea',descSv:'Tränar bröst, axlar, triceps och bål med den egna kroppen som motstånd.',descEn:'Builds the chest, shoulders, triceps and core using bodyweight resistance.',muscles:'Bröst · Triceps',stepsSv:['Placera händerna strax bredare än axlarna.','Håll kroppen i en rak linje.','Sänk bröstet kontrollerat och pressa upp.'],stepsEn:['Place hands slightly wider than shoulders.','Keep the body in one straight line.','Lower the chest with control and press up.']},
  {id:'plank',sv:'Plankan',en:'Plank',cat:'Bål',level:'Nybörjare',time:'5 min',icon:'04',color:'#e6dfef',descSv:'En isometrisk övning som utvecklar uthållighet och kontroll i hela bålen.',descEn:'An isometric exercise that develops endurance and control throughout the core.',muscles:'Bål · Axlar',stepsSv:['Placera armbågarna under axlarna.','Spänn mage och säte.','Behåll en rak linje och andas lugnt.'],stepsEn:['Place elbows under shoulders.','Brace your core and glutes.','Hold a straight line and breathe calmly.']},
  {id:'bridge',sv:'Höftlyft',en:'Glute bridge',cat:'Ben',level:'Nybörjare',time:'7 min',icon:'05',color:'#f0ddda',descSv:'Aktiverar säte och baksida lår samtidigt som höften tränas i extension.',descEn:'Activates glutes and hamstrings while training hip extension.',muscles:'Säte · Baksida lår',stepsSv:['Ligg på rygg med böjda knän.','Pressa fötterna i golvet.','Lyft höften och spänn sätet i toppläget.'],stepsEn:['Lie on your back with knees bent.','Press your feet into the floor.','Lift the hips and squeeze the glutes at the top.']},
  {id:'deadbug',sv:'Död insekt',en:'Dead bug',cat:'Bål',level:'Medel',time:'6 min',icon:'06',color:'#dce9e0',descSv:'Tränar djup bålstabilitet och koordination med låg belastning på ryggen.',descEn:'Trains deep core stability and coordination with low load on the back.',muscles:'Djup bål',stepsSv:['Ligg på rygg med armar och ben upp.','Pressa ländryggen lätt mot golvet.','Sänk motsatt arm och ben långsamt.'],stepsEn:['Lie on your back with arms and legs raised.','Gently press the lower back into the floor.','Slowly lower the opposite arm and leg.']},
  {id:'row',sv:'Rodd med gummiband',en:'Band row',cat:'Överkropp',level:'Nybörjare',time:'8 min',icon:'07',color:'#eee5cf',descSv:'En dragövning för övre rygg, skuldror och armar.',descEn:'A pulling exercise for the upper back, shoulder blades and arms.',muscles:'Rygg · Biceps',stepsSv:['Fäst bandet stadigt framför dig.','Dra armbågarna bakåt nära kroppen.','För händerna långsamt fram igen.'],stepsEn:['Anchor the band securely in front of you.','Pull elbows back close to the body.','Return the hands forward slowly.']},
  {id:'calf',sv:'Tåhävning',en:'Calf raise',cat:'Ben',level:'Nybörjare',time:'5 min',icon:'08',color:'#dde6ed',descSv:'Stärker vader och fotleder och kan förbättra balans och löpekonomi.',descEn:'Strengthens calves and ankles and may improve balance and running economy.',muscles:'Vader · Fotled',stepsSv:['Stå upprätt med jämn vikt på framfoten.','Lyft hälarna så högt du kan.','Sänk långsamt tillbaka.'],stepsEn:['Stand tall with even pressure through the forefoot.','Lift the heels as high as comfortable.','Lower back down slowly.']}
];

const state={language:localStorage.getItem('flex-language')||'both',filter:'Alla',query:'',saved:new Set(JSON.parse(localStorage.getItem('flex-saved')||'[]'))};
const grid=document.querySelector('#exerciseGrid'),filters=document.querySelector('#filters'),count=document.querySelector('#resultCount'),empty=document.querySelector('#emptyState');
const categoryLabels={Alla:'Alla · All',Ben:'Ben · Legs',Överkropp:'Överkropp · Upper body',Bål:'Bål · Core'};
function visibleName(ex){return state.language==='en'?ex.en:ex.sv}function secondName(ex){return state.language==='both'?(visibleName(ex)===ex.sv?ex.en:ex.sv):''}
function setupFilters(){filters.innerHTML=Object.keys(categoryLabels).map(c=>`<button class="filter ${state.filter===c?'active':''}" data-filter="${c}">${categoryLabels[c]}</button>`).join('')}
function render(){const q=state.query.toLowerCase().trim();const found=exercises.filter(e=>(state.filter==='Alla'||e.cat===state.filter)&&(`${e.sv} ${e.en} ${e.cat} ${e.muscles}`).toLowerCase().includes(q));count.textContent=`${found.length} övningar`;empty.hidden=found.length>0;grid.innerHTML=found.map(e=>`<button class="exercise-card" data-id="${e.id}"><span class="save ${state.saved.has(e.id)?'saved':''}" data-save="${e.id}" aria-label="Spara ${e.sv}">${state.saved.has(e.id)?'♥':'♡'}</span><span class="card-art" style="--card:${e.color}">${e.image?`<img src="${e.image}" alt="${e.sv} – ${e.en}" loading="lazy">`:`<span class="stick-figure">${e.icon}</span>`}<span class="card-badge">${e.cat}</span></span><span class="card-copy"><h3>${visibleName(e)}</h3>${secondName(e)?`<p class="secondary">${secondName(e)}</p>`:''}<span class="meta"><span>◷ ${e.time}</span><span>◇ ${e.level}</span></span></span></button>`).join('')}
function openExercise(id){const e=exercises.find(x=>x.id===id),modal=document.querySelector('#exerciseModal');const hasGallery=e.images?.length;const desc=state.language==='en'?e.descEn:e.descSv;const secondDesc=state.language==='both'?e.descEn:'';const steps=state.language==='en'?e.stepsEn:e.stepsSv;document.querySelector('#detailContent').innerHTML=`${hasGallery?`<div class="gallery" id="gallery">${e.images.map((img,i)=>`<figure><img src="${img}" alt="${e.sv}, steg ${i+1}"><figcaption>Steg ${i+1} · Step ${i+1}</figcaption></figure>`).join('')}</div><div class="dots">${e.images.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide="${i}" aria-label="Visa steg ${i+1}"></button>`).join('')}</div>`:`<div class="card-art" style="--card:${e.color};height:230px"><span class="stick-figure">${e.icon}</span></div>`}<div class="detail-copy"><span class="tag">${e.cat} · ${e.level}</span><h2 id="detailTitle">${visibleName(e)}</h2>${secondName(e)?`<p class="translated">${secondName(e)}</p>`:''}<p class="description">${desc}${secondDesc?`<br><br>${secondDesc}`:''}</p><div class="stats"><div class="stat"><span>Tid · Time</span><b>${e.time}</b></div><div class="stat"><span>Nivå · Level</span><b>${e.level}</b></div><div class="stat"><span>Fokus · Focus</span><b>${e.muscles}</b></div></div><div class="instructions"><h3>${state.language==='en'?'How to do it':'Så gör du'}${state.language==='both'?' · How to do it':''}</h3><ol>${steps.map(s=>`<li>${s}</li>`).join('')}</ol></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('body-locked');if(hasGallery){const gallery=document.querySelector('#gallery'),dots=[...document.querySelectorAll('.dot')];gallery.addEventListener('scroll',()=>{const i=Math.round(gallery.scrollLeft/gallery.clientWidth);dots.forEach((d,n)=>d.classList.toggle('active',n===i))},{passive:true});dots.forEach(d=>d.onclick=()=>gallery.scrollTo({left:Number(d.dataset.slide)*gallery.clientWidth,behavior:'smooth'}))}}
function closeModal(){document.querySelector('#exerciseModal').classList.remove('open');document.querySelector('#exerciseModal').setAttribute('aria-hidden','true');document.body.classList.remove('body-locked')}
filters.onclick=e=>{if(e.target.dataset.filter){state.filter=e.target.dataset.filter;setupFilters();render()}};grid.onclick=e=>{const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('flex-saved',JSON.stringify([...state.saved]));render();return}const card=e.target.closest('[data-id]');if(card)openExercise(card.dataset.id)};
document.querySelector('#searchInput').oninput=e=>{state.query=e.target.value;render()};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#searchInput').focus()}if(e.key==='Escape')closeModal()});document.querySelectorAll('[data-close]').forEach(el=>el.onclick=closeModal);
const languageButton=document.querySelector('#languageButton'),languageMenu=document.querySelector('#languageMenu');languageButton.onclick=()=>{languageMenu.hidden=!languageMenu.hidden;languageButton.setAttribute('aria-expanded',String(!languageMenu.hidden))};languageMenu.onclick=e=>{const lang=e.target.closest('[data-language]')?.dataset.language;if(!lang)return;state.language=lang;localStorage.setItem('flex-language',lang);document.querySelector('#languageShort').textContent=lang==='both'?'SV + EN':lang.toUpperCase();languageMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.language===lang));languageMenu.hidden=true;render()};
document.querySelector('#savedLink').onclick=e=>{e.preventDefault();state.query='';document.querySelector('#searchInput').value='';state.filter='Alla';setupFilters();const saved=[...state.saved];if(saved.length){grid.innerHTML=exercises.filter(x=>state.saved.has(x.id)).map(e=>`<button class="exercise-card" data-id="${e.id}"><span class="card-art" style="--card:${e.color}">${e.image?`<img src="${e.image}" alt="${e.sv}">`:`<span class="stick-figure">${e.icon}</span>`}</span><span class="card-copy"><h3>${visibleName(e)}</h3>${secondName(e)?`<p class="secondary">${secondName(e)}</p>`:''}</span></button>`).join('');count.textContent=`${saved.length} sparade`}else{render();empty.hidden=false;empty.querySelector('h3').textContent='Inga sparade övningar än';empty.querySelector('p').textContent='Tryck på hjärtat på en övning för att spara den.'}document.querySelector('#libraryTitle').scrollIntoView()};
document.querySelector('#languageShort').textContent=state.language==='both'?'SV + EN':state.language.toUpperCase();languageMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.language===state.language));setupFilters();render();
