(function(){
  const x=(id,sv,en,cat,position,muscles,issues,weaknesses,svSteps,enSteps)=>({id,sv,en,aliases:[en],cat,level:'Nybörjare',time:'5–10 min',muscles,position,issues,weaknesses,descSv:`En lugn ${cat.toLowerCase()}övning för ${muscles.join(', ').toLowerCase()} med fokus på kontroll och bekväm rörelse.`,descEn:`A gentle ${cat.toLowerCase()} exercise for ${muscles.join(', ').toLowerCase()}, focused on control and a comfortable range.`,stepsSv:svSteps,stepsEn:enSteps,variations:[`Mindre rörelse · Smaller range`,`Med stöd · With support`,`Långsamt tempo · Slow tempo`],images:[],image:null});
  globalThis.flexAdditionalExercises=[
    x('yoga-catcow','Katt och ko','Cat–cow','Yoga','Fyrfota',['Rygg','Bål'],['Nacke','Övre rygg','Ländrygg'],['Rörlighet','Bål'],['Stå på alla fyra.','Runda ryggen mjukt.','Växla till en försiktig svank.'],['Start on all fours.','Gently round the spine.','Move into a gentle arch.']),
    x('yoga-child','Barnets position','Child’s pose','Yoga','Knästående',['Rygg','Höft'],['Övre rygg','Ländrygg','Höfter'],['Rörlighet'],['Sitt bak mot hälarna.','Sträck armarna framåt.','Andas lugnt utan att pressa.'],['Sit back toward the heels.','Reach the arms forward.','Breathe calmly without forcing.']),
    x('yoga-dog','Nedåtgående hund','Downward-facing dog','Yoga','Händer och fötter',['Axlar','Rygg','Baksida lår'],['Axlar','Övre rygg','Baksida lår'],['Axlar','Rörlighet'],['Börja på alla fyra.','Lyft höfterna bakåt och uppåt.','Böj knäna vid behov.'],['Start on all fours.','Lift the hips back and up.','Bend the knees if needed.']),
    x('yoga-warrior2','Krigare två','Warrior II','Yoga','Stående',['Ben','Höft','Axlar'],['Höfter','Knän','Axlar'],['Ben','Balans'],['Ta ett brett steg.','Böj främre knät och sträck armarna.','Håll bröstkorgen centrerad.'],['Take a wide stance.','Bend the front knee and reach the arms.','Keep the torso centered.']),

    x('pilates-hundred','Hundringen','The hundred','Pilates','Ryggläge',['Bål'],['Ländrygg'],['Bål','Uthållighet'],['Ligg med benen i bordsläge.','Lyft huvud vid behov och pumpa armarna.','Andas rytmiskt.'],['Lie with legs in tabletop.','Lift the head if comfortable and pump the arms.','Breathe rhythmically.']),
    x('pilates-rollup','Upprullning','Roll-up','Pilates','Ryggläge',['Bål','Rygg'],['Ländrygg','Övre rygg'],['Bål','Rörlighet'],['Ligg utsträckt.','Rulla långsamt upp kota för kota.','Rulla kontrollerat tillbaka.'],['Lie long.','Roll up slowly one vertebra at a time.','Roll back with control.']),
    x('pilates-singleleg','Enbenssträck','Single-leg stretch','Pilates','Ryggläge',['Bål','Höft'],['Ländrygg','Höfter'],['Bål'],['Dra ett knä mot bröstet.','Sträck motsatt ben.','Växla utan att ryggen lyfter.'],['Draw one knee toward the chest.','Extend the opposite leg.','Switch without lifting the back.']),
    x('pilates-clam','Musslan','Clamshell','Pilates','Sidoläge',['Säte','Höft'],['Höfter','Knän'],['Säte','Höft'],['Ligg på sidan med böjda knän.','Håll fötterna ihop.','Öppna övre knät utan att rulla bäckenet.'],['Lie on the side with knees bent.','Keep the feet together.','Open the top knee without rolling the pelvis.']),

    x('qigong-lifeg','Lyfta himlen','Lifting the sky','Qi gong','Stående',['Axlar','Rygg'],['Nacke','Axlar','Övre rygg'],['Rörlighet','Andning'],['Stå mjukt i knäna.','För händerna långsamt uppåt.','Sänk dem med en lugn utandning.'],['Stand with soft knees.','Float the hands slowly upward.','Lower them with a calm exhale.']),
    x('qigong-cloud','Molnhänder','Cloud hands','Qi gong','Stående',['Axlar','Bål'],['Axlar','Övre rygg'],['Koordination','Balans'],['Flytta vikten lugnt sida till sida.','Låt händerna cirkla framför kroppen.','Följ rörelsen med blicken.'],['Shift weight slowly side to side.','Circle the hands in front of the body.','Follow the movement with the eyes.']),
    x('qigong-bow','Spänna bågen','Drawing the bow','Qi gong','Stående',['Rygg','Axlar'],['Axlar','Övre rygg'],['Rygg','Hållning'],['Stå brett och mjukt.','För ena handen ut som en båge.','Återgå och byt sida.'],['Stand wide and relaxed.','Extend one hand as if drawing a bow.','Return and switch sides.']),
    x('qigong-wave','Vågrörelse','Qigong wave','Qi gong','Stående',['Helkropp','Höft'],['Höfter','Ländrygg'],['Koordination','Rörlighet'],['Gunga vikten fram och tillbaka.','Låt rörelsen färdas genom kroppen.','Behåll en lugn andning.'],['Rock the weight forward and back.','Let the motion travel through the body.','Keep the breath calm.']),

    x('taichi-open','Öppna och sluta','Open and close','Tai chi','Stående',['Axlar','Bål'],['Axlar','Övre rygg'],['Koordination','Hållning'],['Håll händerna framför bröstet.','Öppna armarna långsamt.','För dem mjukt tillbaka.'],['Hold the hands before the chest.','Open the arms slowly.','Bring them gently back.']),
    x('taichi-partmane','Dela hästens man','Parting the wild horse’s mane','Tai chi','Stående',['Ben','Bål'],['Höfter','Knän'],['Balans','Ben'],['Flytta vikten till ena benet.','Steg fram och dela händerna.','Samla ihop och byt sida.'],['Shift weight to one leg.','Step forward and separate the hands.','Gather and switch sides.']),
    x('taichi-rooster','Guldtuppen står','Golden rooster stands','Tai chi','Stående',['Ben','Bål'],['Fötter','Knän','Höfter'],['Balans','Ben'],['Stå nära ett stöd.','Lyft ett knä och motsatt hand.','Sänk kontrollerat och byt.'],['Stand near support.','Lift one knee and the opposite hand.','Lower with control and switch.']),
    x('taichi-wave','Vifta bort moln','Wave hands like clouds','Tai chi','Stående',['Bål','Ben'],['Övre rygg','Höfter'],['Koordination','Balans'],['Ta små sidosteg.','Rotera mjukt från midjan.','Låt händerna passera framför kroppen.'],['Take small side steps.','Rotate gently from the waist.','Let the hands pass before the body.']),

    x('eyes-palming','Avslappning med kupade händer','Palming','Ögonträning','Sittande',['Ögon','Avslappning'],['Ögontrötthet'],['Avslappning'],['Värm handflatorna.','Kupa dem löst över slutna ögon utan tryck.','Vila och andas lugnt.'],['Warm the palms.','Cup them loosely over closed eyes without pressure.','Rest and breathe calmly.']),
    x('eyes-nearfar','Fokus nära och långt','Near–far focus','Ögonträning','Sittande',['Ögon'],['Ögontrötthet'],['Fokuskontroll'],['Titta på ett föremål nära.','Flytta blicken till något långt bort.','Växla långsamt utan att anstränga.'],['Look at a nearby object.','Shift focus to something far away.','Alternate slowly without straining.']),
    x('eyes-figure8','Blick i liggande åtta','Figure-eight tracking','Ögonträning','Sittande',['Ögon'],['Ögontrötthet'],['Blickkontroll'],['Håll huvudet stilla.','Följ en långsam liggande åtta med blicken.','Byt riktning.'],['Keep the head still.','Trace a slow horizontal figure eight with the eyes.','Reverse direction.']),
    x('eyes-blink','Medveten blinkning','Conscious blinking','Ögonträning','Sittande',['Ögon'],['Ögontrötthet'],['Avslappning'],['Slappna av i käke och panna.','Blunda mjukt en sekund.','Öppna och upprepa utan att knipa.'],['Relax the jaw and forehead.','Close the eyes softly for one second.','Open and repeat without squeezing.']),

    x('neck-chintuck','Hakindrag','Chin tuck','Nackträning','Sittande',['Nacke','Hållning'],['Nacke','Huvudvärk'],['Nacke','Hållning'],['Sitt högt och titta framåt.','För hakan rakt bakåt.','Slappna av utan att böja huvudet.'],['Sit tall and look forward.','Glide the chin straight back.','Release without tipping the head.']),
    x('neck-rotation','Nackrotation','Neck rotation','Nackträning','Sittande',['Nacke'],['Nacke'],['Rörlighet'],['Sitt med avslappnade axlar.','Vrid huvudet långsamt åt sidan.','Återgå och byt sida.'],['Sit with relaxed shoulders.','Turn the head slowly to one side.','Return and switch sides.']),
    x('neck-isometric','Isometrisk nackpress','Isometric neck press','Nackträning','Sittande',['Nacke'],['Nacke'],['Nacke'],['Placera handen mot pannan.','Pressa mycket lätt utan att huvudet rör sig.','Släpp och upprepa åt sidorna.'],['Place a hand on the forehead.','Press very gently without moving the head.','Release and repeat to the sides.']),
    x('neck-shoulderroll','Axelrullning','Shoulder roll','Nackträning','Sittande',['Nacke','Axlar'],['Nacke','Axlar'],['Rörlighet','Hållning'],['Lyft axlarna lätt.','Rulla dem bakåt och nedåt.','Fortsätt långsamt utan smärta.'],['Lift the shoulders gently.','Roll them back and down.','Continue slowly without pain.']),

    x('ball-wall-squat','Knäböj mot pilatesboll','Swiss-ball wall squat','Pilatesboll','Stående',['Lår','Säte'],['Knän','Höfter'],['Ben'],['Placera bollen mellan rygg och vägg.','Gå fram med fötterna.','Böj och sträck benen kontrollerat.'],['Place the ball between back and wall.','Walk the feet forward.','Bend and straighten the legs with control.']),
    x('ball-bridge','Höftlyft med boll','Ball bridge','Pilatesboll','Ryggläge',['Säte','Baksida lår'],['Ländrygg','Höfter'],['Säte','Bål'],['Lägg underbenen på bollen.','Spänn bålen.','Lyft höfterna utan att bollen rullar.'],['Place the lower legs on the ball.','Brace the core.','Lift the hips without rolling the ball.']),
    x('ball-kneel','Knästående bollbalans','Ball kneeling balance','Pilatesboll','Knästående',['Bål','Höft'],['Höfter'],['Balans','Bål'],['Ha stöd nära och knästå på bollen.','Håll blicken stilla.','Balansera korta stunder.'],['Keep support nearby and kneel on the ball.','Fix the gaze.','Balance for short periods.']),
    x('ball-curl','Lårcurl med boll','Ball hamstring curl','Pilatesboll','Ryggläge',['Baksida lår','Säte'],['Knän','Höfter'],['Baksida lår'],['Ligg med hälarna på bollen.','Lyft höfterna.','Rulla bollen in och ut.'],['Lie with heels on the ball.','Lift the hips.','Roll the ball in and out.']),

    x('roller-thoracic','Bröstrygg över rulle','Thoracic extension on roller','Pilatesrulle','Ryggläge',['Övre rygg'],['Övre rygg','Axlar'],['Rörlighet','Hållning'],['Placera rullen tvärs under bröstryggen.','Stöd huvudet med händerna.','Luta varsamt bakåt.'],['Place the roller across the upper back.','Support the head with the hands.','Gently extend backward.']),
    x('roller-calf','Vadrullning','Calf foam rolling','Pilatesrulle','Sittande, ben framåt',['Vader'],['Vader','Fötter'],['Rörlighet'],['Placera vaden på rullen.','Stöd med händerna.','Rulla långsamt över ett bekvämt område.'],['Place the calf on the roller.','Support with the hands.','Roll slowly over a comfortable area.']),
    x('roller-glute','Sätesrullning','Glute foam rolling','Pilatesrulle','Sittande',['Säte'],['Höfter','Säte'],['Rörlighet'],['Sitt med ena skinkan på rullen.','Stöd dig med händerna.','Rulla långsamt utan skarp smärta.'],['Sit with one glute on the roller.','Support yourself with the hands.','Roll slowly without sharp pain.']),
    x('roller-balance','Stabilitet längs rullen','Long roller balance','Pilatesrulle','Ryggläge',['Bål'],['Ländrygg'],['Bål','Balans'],['Ligg längs rullen.','Placera fötterna stadigt.','Lyft en arm i taget utan att tappa balansen.'],['Lie lengthwise on the roller.','Plant the feet firmly.','Lift one arm at a time without losing balance.']),

    x('hands-fist','Öppna och knyt handen','Open and close fist','Handträning','Sittande',['Händer','Fingrar'],['Händer','Fingrar'],['Grepp'],['Sträck fingrarna mjukt.','Knyt handen utan att pressa.','Öppna långsamt igen.'],['Gently extend the fingers.','Make a fist without squeezing hard.','Open slowly again.']),
    x('hands-thumb','Tummens fingertouch','Thumb-to-finger touch','Handträning','Sittande',['Händer','Fingrar'],['Tumme','Fingrar'],['Koordination'],['För tummen till pekfingret.','Fortsätt till varje fingertopp.','Återgå lugnt.'],['Touch the thumb to the index finger.','Continue to each fingertip.','Return calmly.']),
    x('hands-wrist','Handledscirklar','Wrist circles','Handträning','Sittande',['Handleder','Händer'],['Handleder','Händer'],['Rörlighet'],['Håll underarmarna stilla.','Rita små cirklar med handlederna.','Byt riktning.'],['Keep the forearms still.','Draw small circles with the wrists.','Reverse direction.']),
    x('hands-towel','Handdukspress','Towel squeeze','Handträning','Sittande',['Händer','Underarmar'],['Händer'],['Grepp'],['Rulla en mjuk handduk.','Pressa lätt i några sekunder.','Släpp helt mellan repetitionerna.'],['Roll a soft towel.','Squeeze gently for a few seconds.','Release fully between repetitions.']),

    x('feet-toeyoga','Tåyoga','Toe yoga','Fotträning','Sittande',['Fötter','Tår'],['Fötter','Tår'],['Fötter'],['Håll hälen i golvet.','Lyft stortån medan övriga tår ligger kvar.','Byt och upprepa.'],['Keep the heel on the floor.','Lift the big toe while the others stay down.','Switch and repeat.']),
    x('feet-arch','Kort fot','Short-foot exercise','Fotträning','Stående',['Fotvalv'],['Fötter'],['Fötter','Balans'],['Stå med jämnt tryck.','Dra trampdynan lätt mot hälen.','Behåll tårna avslappnade.'],['Stand with even pressure.','Gently draw the ball of the foot toward the heel.','Keep the toes relaxed.']),
    x('feet-ankle','Fotledsalfabet','Ankle alphabet','Fotträning','Sittande',['Fotled','Fötter'],['Fötter','Fotleder'],['Rörlighet'],['Lyft ena foten.','Rita alfabetet smått med foten.','Byt fot utan att röra knät mycket.'],['Lift one foot.','Draw the alphabet small with the foot.','Switch feet without moving the knee much.']),
    x('feet-towel','Handduksdrag med tår','Towel scrunch','Fotträning','Sittande',['Fötter','Tår'],['Fötter','Tår'],['Fötter'],['Lägg en handduk under foten.','Dra den mot dig med tårna.','Slappna av mellan dragen.'],['Place a towel under the foot.','Pull it toward you with the toes.','Relax between pulls.']),

    x('posture-wall','Vägglinjering','Wall alignment','Hållning','Stående',['Hållning','Rygg'],['Nacke','Övre rygg','Ländrygg'],['Hållning'],['Stå med rygg mot väggen.','Låt bakhuvud och bäcken närma sig väggen bekvämt.','Andas utan att spänna.'],['Stand with the back to a wall.','Let the head and pelvis approach the wall comfortably.','Breathe without bracing.']),
    x('posture-wallangel','Väggängel','Wall angel','Hållning','Stående',['Axlar','Övre rygg'],['Axlar','Övre rygg'],['Hållning','Axlar'],['Stå mot en vägg.','För armarna långsamt uppåt.','Behåll revbenen avslappnade.'],['Stand against a wall.','Slide the arms slowly upward.','Keep the ribs relaxed.']),
    x('posture-scapula','Skulderbladssamling','Scapular retraction','Hållning','Sittande',['Övre rygg','Axlar'],['Nacke','Axlar','Övre rygg'],['Rygg','Hållning'],['Sitt högt med armarna avslappnade.','För skulderbladen lätt bakåt och nedåt.','Släpp helt.'],['Sit tall with relaxed arms.','Draw the shoulder blades gently back and down.','Release fully.']),
    x('posture-hiphinge','Höftfällning','Hip hinge','Hållning','Stående',['Rygg','Höft'],['Ländrygg','Höfter'],['Hållning','Säte'],['Stå mjukt i knäna.','Skjut höfterna bakåt med lång rygg.','Pressa höfterna fram till stående.'],['Stand with soft knees.','Push the hips back with a long spine.','Drive the hips forward to stand.']),

    x('face-cheek','Kindlyft','Cheek lift','Ansiktsövningar','Sittande',['Ansikte'],['Käkspänning'],['Ansiktskontroll'],['Slappna av i käken.','Le mjukt och lyft kinderna.','Släpp utan att kisa.'],['Relax the jaw.','Smile gently and lift the cheeks.','Release without squinting.']),
    x('face-jaw','Avslappnad käköppning','Relaxed jaw opening','Ansiktsövningar','Sittande',['Käke'],['Käkspänning'],['Avslappning'],['Låt tungan vila.','Öppna munnen en liten bit.','Stäng mjukt utan att bita ihop.'],['Let the tongue rest.','Open the mouth a small amount.','Close gently without clenching.']),
    x('face-lips','Läpptrill','Lip trill','Ansiktsövningar','Sittande',['Ansikte','Andning'],['Käkspänning'],['Avslappning'],['Slappna av i läpparna.','Blås ut så att läpparna vibrerar lätt.','Pausa om du blir yr.'],['Relax the lips.','Exhale so the lips vibrate gently.','Pause if you feel dizzy.']),
    x('face-brow','Pannavslappning','Brow relaxation','Ansiktsövningar','Sittande',['Ansikte'],['Huvudvärk','Ögontrötthet'],['Avslappning'],['Placera fingertopparna lätt över ögonbrynen.','Släpp spänningen i pannan.','Andas lugnt utan att dra i huden.'],['Rest fingertips lightly above the brows.','Release tension in the forehead.','Breathe calmly without pulling the skin.']),

    x('stretch-hamstring','Sittande baksidalårstretch','Seated hamstring stretch','Stretching','Sittande, ben framåt',['Baksida lår'],['Baksida lår','Ländrygg'],['Rörlighet'],['Sitt högt med ett ben framåt.','Fäll lätt från höften.','Stanna före smärta.'],['Sit tall with one leg forward.','Hinge gently from the hip.','Stop before pain.']),
    x('stretch-hipflexor','Höftböjarstretch','Hip-flexor stretch','Stretching','Knästående',['Höft'],['Höfter','Ländrygg'],['Rörlighet'],['Stå i halvt knästående.','Tippa bäckenet lätt bakåt.','Flytta vikten fram utan att svanka.'],['Start half-kneeling.','Gently tuck the pelvis.','Shift forward without arching the back.']),
    x('stretch-chest','Bröststretch i dörröppning','Doorway chest stretch','Stretching','Stående',['Bröst','Axlar'],['Axlar','Övre rygg'],['Rörlighet','Hållning'],['Placera underarmen mot en dörrpost.','Ta ett litet steg fram.','Håll axeln avslappnad.'],['Place the forearm on a doorway.','Take a small step forward.','Keep the shoulder relaxed.']),
    x('stretch-calf','Vadstretch mot vägg','Wall calf stretch','Stretching','Stående',['Vader','Fotled'],['Vader','Fötter'],['Rörlighet'],['Sätt händerna mot väggen.','Steg bak med ena foten.','Håll hälen nere och knät rakt.'],['Place the hands on a wall.','Step one foot back.','Keep the heel down and knee straight.'])
  ];
})();
